id: 8db92ea776124b4ba5ed47f05bba1555
initial_creation_type: ocr
source_metadata:
  volumes:
    2dacf66f4f0b4da693bbb92cde9c6bd8:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: ཁ་ཏོན་དང་གླེགས་བམ་ཀླག་པའི་སྔོན་དུ་བྱ་བའི་ཆོ་ག།
      total_pages: 1498
      volume_number: 65
